version: '3'

services:
  mongo:
    image:  mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  server:
    build: .
    volumes:
      - ./:/app:Z
    environment:
      - MONGODB_ENDPOINT=mongo:27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
      - WAIT_HOSTS=mongo:27017
    links:
      - mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo