version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scoresfoot

  server:
    build: .
    volumes:
      - ./src:/app/src
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_ENDPOINT=db:5432
    links:
      - db
    ports:
      - "8081:8081"
    depends_on:
      - db